/*
 * Ziti Edge Client
 * Hanzo ZT Edge Client API
 *
 * The version of the OpenAPI document: 0.26.53
 * Contact: help@hanzozt.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.hanzozt.edge;

import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2026-02-17T13:48:12.956235-05:00[America/New_York]",
        comments = "Generator version: 7.20.0")
public class Configuration {
    public static final String VERSION = "0.31.2-bump-edge-api-8.fea3ec8-dirty-SNAPSHOT";

    private static final AtomicReference<ApiClient> defaultApiClient = new AtomicReference<>();
    private static volatile Supplier<ApiClient> apiClientFactory = ApiClient::new;

    /**
     * Get the default API client, which would be used when creating API instances without providing
     * an API client.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        ApiClient client = defaultApiClient.get();
        if (client == null) {
            client =
                    defaultApiClient.updateAndGet(
                            val -> {
                                if (val != null) { // changed by another thread
                                    return val;
                                }
                                return apiClientFactory.get();
                            });
        }
        return client;
    }

    /**
     * Set the default API client, which would be used when creating API instances without providing
     * an API client.
     *
     * @param apiClient API client
     */
    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient.set(apiClient);
    }

    /** set the callback used to create new ApiClient objects */
    public static void setApiClientFactory(Supplier<ApiClient> factory) {
        apiClientFactory = Objects.requireNonNull(factory);
    }

    private Configuration() {}
}
