/*
 * Ziti Edge Management
 * Hanzo ZT Edge Management API
 *
 * The version of the OpenAPI document: 0.26.53
 * Contact: help@hanzozt.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.hanzozt.management;

@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2026-02-17T13:51:23.777813-05:00[America/New_York]",
        comments = "Generator version: 7.20.0")
public class Pair {
    private final String name;
    private final String value;

    public Pair(String name, String value) {
        this.name = isValidString(name) ? name : "";
        this.value = isValidString(value) ? value : "";
    }

    public String getName() {
        return this.name;
    }

    public String getValue() {
        return this.value;
    }

    private static boolean isValidString(String arg) {
        return arg != null;
    }
}
